### ISSUE TITLE
mcrypt_encrypt()

### ISSUE THREAD

**Issue by roy13** [emoncms/event#50]
Changes to php 5.6 no longer auto pad encryption keys. Therefore event needs modifications or use php < 5.6 Which comes with Jessie.

**Comment by elyobelyob** [comment]
Can I remove event?

**Comment by roy13** [comment]
Please no, event is one of my most used features. Is someone able to add padding to the keys smtp password & mqtt password etc. Probably not so hard for someone who knows what they are doing. I've tried but have not enough php skill.

**Comment by roy13** [comment]
I forgot to mention my colleague & i got it working on emoncms 9 have been using it for 6months now. Im not sure how to upload the working code? Should i just post it here?

**Comment by elyobelyob** [comment]
Not sure to be honest. I think it's now legacy. I'd keep a working copy in
your own github.

I have removed my original copy of event, but as it seems everyone was
using emoncms' copy anyway.

So, it'll survive as long as it does. I'm perfectly happy with the
alternative MQTT solution, and am interested in MQTTWarn, but not got that
going yet.

Node-red is a very fun development tool as well.

I'd look beyond the event module. It was overly heavy on API usage anyway.

A bit of a dirty hack, best left in the past!

But keep a copy yourself via github, if you need it.

**Comment by glynhudson** [comment]
I have added a 'legacy note' the event readme
